# This file was generated by GoReleaser. DO NOT EDIT.
cask "dcctl" do
  name "dcctl"
  desc "Docker Compose Control - manage Compose stacks per environment"
  homepage "https://github.com/hrodrig/dcctl"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dcctl"

  on_macos do
    on_intel do
      url "https://github.com/hrodrig/dcctl/releases/download/v#{version}/dcctl_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/dcctl/"
      sha256 "14c89a7855a9dfdc143546a32fd92e905f5a615ce0f94fa7cf98f085c4cb9f4b"
    end
    on_arm do
      url "https://github.com/hrodrig/dcctl/releases/download/v#{version}/dcctl_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/dcctl/"
      sha256 "f71cf66d4a4cb2102c9a6cf79423e1e852e32bad871fbd423dbf84f419aff085"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hrodrig/dcctl/releases/download/v#{version}/dcctl_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/dcctl/"
      sha256 "e4c467434d2091f84cc7ec0c305453ef252d3a8cddc1038d268dfee39e46205c"
    end
    on_arm do
      url "https://github.com/hrodrig/dcctl/releases/download/v#{version}/dcctl_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/dcctl/"
      sha256 "098920313f7229edffabdf46eb743ae4297a3b36e449673164a4b27d116ac07c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dcctl"]
    end
  end

  # No zap stanza required
end
