# This file was generated by GoReleaser. DO NOT EDIT.
cask "dcctl" do
  name "dcctl"
  desc "Docker Compose Control - manage Compose stacks per environment"
  homepage "https://github.com/hrodrig/dcctl"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dcctl"

  on_macos do
    on_intel do
      url "https://github.com/hrodrig/dcctl/releases/download/v#{version}/dcctl_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/dcctl/"
      sha256 "e8fa7d2cc78343cec4d149ca87134c9ffde2a6641ec91454b6225e0d2075956c"
    end
    on_arm do
      url "https://github.com/hrodrig/dcctl/releases/download/v#{version}/dcctl_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/dcctl/"
      sha256 "afab03f157d81c5e5bf48be9694965318b44b94a3c9c0e65b1554eb7fd0130b2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hrodrig/dcctl/releases/download/v#{version}/dcctl_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/dcctl/"
      sha256 "0119f0c4356b6e901123098c3ba32c15b1920a2a787e98911901a613f70756a1"
    end
    on_arm do
      url "https://github.com/hrodrig/dcctl/releases/download/v#{version}/dcctl_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/dcctl/"
      sha256 "ec39aa43d50750959dfb585551719fb3941dde2d88b5ccf11f842ffa5af5c75c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dcctl"]
    end
  end

  # No zap stanza required
end
